Update __init__.py
Path object is directly passed to pkgutil.iter_modules() which is causing AttributeError: 'PosixPath' object has no attribute 'startswith'